spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/Auth_service?useSSL=false&allowPublicKeyRetrieval=true
    username: klatos
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretKey: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG